export { default as Clock } from './Clock'
export { default as Mpris } from './Mpris'
export { default as Pacman } from './Pacman'
export { default as QuickSettings } from './QuickSettings'
export { default as Workspace } from './Workspace'
